<a href="https://colab.research.google.com/github/hariharan13052003/Churn-Analysis-Project/blob/main/ChurnAnalysis_RandomForestTried.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import the required libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('Churn_Modelling.csv')

In [ ]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
data.shape

(10000, 14)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [ ]:
# missing values

data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
churndf = data.drop(columns = ['RowNumber','CustomerId', 'Surname'])

In [ ]:
churndf.shape

(10000, 11)

In [ ]:
# categorical data

churndf.select_dtypes(include = 'object').columns

Index(['Geography', 'Gender'], dtype='object')

In [ ]:
churndf.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
churndf = pd.get_dummies(data = churndf, drop_first = True, dtype = int)

In [ ]:
churndf.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   
2               0        113931.57       1                  0   
3               0         93826.63       0                  0   
4               1         79084.10       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0  
2                0            0  
3                0            0  
4                1            0

In [ ]:
churndf.shape

(10000, 12)

In [ ]:
# splitting the dataset

X = churndf.drop(['Exited'],axis = 1)
Y = churndf['Exited']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 50 ,oob_score = True)

clf.fit(X_train,Y_train)

RandomForestClassifier(oob_score=True, random_state=50)

In [ ]:
clf.oob_score_

0.8601111111111112

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score,precision_score,recall_score

In [ ]:
# train data score

Y_train_pred = clf.predict(X_train)

In [ ]:
acc = accuracy_score(Y_train,Y_train_pred )
f1 = f1_score(Y_train,Y_train_pred )
prec = precision_score(Y_train,Y_train_pred)
rec = recall_score(Y_train,Y_train_pred)

output  = pd.DataFrame([['RandomForest',acc,prec,rec,f1]],
                      columns = ['Model','Accuracy','Precision','Recall','F1 Score'])

In [ ]:
output

Model  Accuracy  Precision  Recall  F1 Score
0  RandomForest       1.0        1.0     1.0       1.0

In [ ]:
# test data score

y_test_pred =clf.predict(X_test)

In [ ]:
Acc = accuracy_score(Y_test,y_test_pred)
F1 = f1_score(Y_test,y_test_pred)
Prec = precision_score(Y_test,y_test_pred)
Rec = recall_score(Y_test,y_test_pred)

Output  = pd.DataFrame([['RandomForest',Acc,F1,Prec,Rec]],
                      columns = ['Model','Accuracy','Precision','Recall','F1 Score'])

In [ ]:
Output

Model  Accuracy  Precision    Recall  F1 Score
0  RandomForest     0.869    0.58147  0.745902   0.47644

In [ ]:
cm = confusion_matrix(Y_train,Y_train_pred)
print(cm)

[[7154    0]
 [   0 1846]]


In [ ]:
cm = confusion_matrix(Y_test,y_test_pred)
print(cm)

[[778  31]
 [100  91]]


In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(clf, X_train, Y_train, cv=10)

In [ ]:
print(scores)

[0.86444444 0.87444444 0.85666667 0.85777778 0.85       0.86333333
 0.87555556 0.85333333 0.86       0.85666667]


In [ ]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))



0.86 accuracy with a standard deviation of 0.01


In [ ]:
Scores = cross_val_score(clf, X_test, Y_test, cv=10)

In [ ]:
print(Scores)

[0.85 0.87 0.85 0.83 0.87 0.88 0.88 0.85 0.86 0.84]


In [ ]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (Scores.mean(), Scores.std()))

0.86 accuracy with a standard deviation of 0.02


In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
parameters = {
    'kernel':['linear', 'rbf'],
    'C':[0.1,1, 10]
    }

In [ ]:
from sklearn import svm
clf2 = svm.SVC()

In [ ]:
grid_search = GridSearchCV(clf2,param_grid=parameters,cv=5,
                           n_jobs=-1,verbose=4)

In [ ]:
grid_search.fit(X_train,Y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


In [ ]:
grid_search.fit(X_train,y_train)